FROM python:3.8

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY jupyter_notebook_config.py /root/.jupyter/

WORKDIR /data

EXPOSE 8888

ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--no-browser", "--allow-root"]